### ISSUE TITLE
Rapid Pipe Device (RPD) is broken

### ISSUE THREAD

**Issue by JoshiBro** [Citadel-Station-13/Citadel-Station-13-RP#3906]
## Round ID:
no clue how, I just saw it now

## Reproduction:
Open the RPD UI

## Code Error:
TypeError: Unable to get property 'undefined' of undefined or null reference
   at m (http://127.0.0.1:49821/tmp11672/tgui.bundle.js:1:855428)
   at Ne (http://127.0.0.1:49821/tmp11672/tgui-common.chunk.js:1:154373)
   at Anonymous function (http://127.0.0.1:49821/tmp11672/tgui-common.chunk.js:1:154641)
   at Fe (http://127.0.0.1:49821/tmp11672/tgui-common.chunk.js:1:154619)
   at Oe (http://127.0.0.1:49821/tmp11672/tgui-common.chunk.js:1:155472)
   at Fe (http://127.0.0.1:49821/tmp11672/tgui-common.chunk.js:1:154483)
   at Anonymous function (http://127.0.0.1:49821/tmp11672/tgui-common.chunk.js:1:154641)
   at Fe (http://127.0.0.1:49821/tmp11672/tgui-common.chunk.js:1:154619)
   at Anonymous function (http://127.0.0.1:49821/tmp11672/tgui-common.chunk.js:1:154641)
   at Fe (http://127.0.0.1:49821/tmp11672/tgui-common.chunk.js:1:154619)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"joshibro","interface":"RapidPipeDispenser","window":{"key":"[0x204f660]-main","size":null,"fancy":1,"locked":1}}

**Comment by Zandario** [comment]
This was due to an outdated Test-Merge. It was fixed by the next round. Super appreciate the Issue report though! <3
